language: python
python:
  - 2.7
  - 3.3
install:
  - pip install codecov
  - pip install flaky
  - python setup.py -q install
script:
  - coverage run --source=jodel_api -m pytest -v -l -ra --no-success-flaky-report
after_success:
  codecov
